# -*- coding: utf-8 -*-
"""
Created on Mon Jun 29 19:01:28 2026

@author: SMMH
"""
import numpy as np
print(":اعداد ماتریس اول را بفرست")
print(" :درایه ی 1")
a=float(input())
print(" :درایه ی 2")
b=float(input())
print(" :درایه ی 3")
c=float(input())
print(" :درایه ی 4")
d=float(input())
print(" :درایه ی 5")
e=float(input())
print(" :درایه ی 6")
f=float(input())
print(" :درایه ی 7")
g=float(input())
print(" :درایه ی 8")
h=float(input())
print(" :درایه ی 9")
i=float(input())
x=np.array([[a,b,c],[d,e,f],[g,h,i]])
print(x)
print(":اعداد ماتریس دوم را بفرست")
print(" :درایه ی 1")
a2=float(input())
print(" :درایه ی 2")
b2=float(input())
print(" :درایه ی 3")
c2=float(input())
print(" :درایه ی 4")
d2=float(input())
print(" :درایه ی 5")
e2=float(input())
print(" :درایه ی 6")
f2=float(input())
print(" :درایه ی 7")
g2=float(input())
print(" :درایه ی 8")
h2=float(input())
print(" :درایه ی 9")
i2=float(input())
y=np.array([[a2,b2,c2],[d2,e2,f2],[g2,h2,i2]])
print(y)
print(":عمل خواسته شده")
print(x),print("*"),print(y),print("=")
z=x@y
print(z)